export const INITIALIZE_AUTH = "INITIALIZE_AUTH";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_USER_DATA = "SET_USER_DATA";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
